"""make_vendor_id_nullable

Revision ID: 66aa16ce2e4d
Revises: dcd583aba8c6
Create Date: 2026-03-04 09:04:06.930092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66aa16ce2e4d'
down_revision: Union[str, None] = 'dcd583aba8c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'vendor_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'vendor_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
