"""add_resolution_plans_and_automation_actions

Revision ID: dcd583aba8c6
Revises: a1b2c3d4e5f6
Create Date: 2026-03-04 07:28:19.806568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcd583aba8c6'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resolution_plans',
    sa.Column('exception_id', sa.UUID(), nullable=False),
    sa.Column('plan_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'executing', 'completed', 'failed', name='plan_status', native_enum=False), nullable=False),
    sa.Column('automation_level', sa.Enum('auto', 'assisted', 'manual', name='automation_level', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('recheck_strategy', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('audit_evidence', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exception_id'], ['exceptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resolution_plans_exception_id', 'resolution_plans', ['exception_id'], unique=False)
    op.create_index(op.f('ix_resolution_plans_id'), 'resolution_plans', ['id'], unique=False)
    op.create_index('ix_resolution_plans_status', 'resolution_plans', ['status'], unique=False)
    op.create_table('automation_actions',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('step_id', sa.String(length=20), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('params_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('pending', 'awaiting_approval', 'running', 'done', 'failed', 'skipped', name='action_status', native_enum=False), nullable=False),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=False),
    sa.Column('risk', sa.String(length=20), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('result_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['resolution_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_automation_actions_id'), 'automation_actions', ['id'], unique=False)
    op.create_index('ix_automation_actions_plan_id', 'automation_actions', ['plan_id'], unique=False)
    op.create_index('ix_automation_actions_status', 'automation_actions', ['status'], unique=False)
    op.add_column('invoices', sa.Column('payment_locked', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'payment_locked')
    op.drop_index('ix_automation_actions_status', table_name='automation_actions')
    op.drop_index('ix_automation_actions_plan_id', table_name='automation_actions')
    op.drop_index(op.f('ix_automation_actions_id'), table_name='automation_actions')
    op.drop_table('automation_actions')
    op.drop_index('ix_resolution_plans_status', table_name='resolution_plans')
    op.drop_index(op.f('ix_resolution_plans_id'), table_name='resolution_plans')
    op.drop_index('ix_resolution_plans_exception_id', table_name='resolution_plans')
    op.drop_table('resolution_plans')
    # ### end Alembic commands ###
